services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: runtime
    container_name: backend
    environment:
      PORT: "8000"
    restart: unless-stopped
  proxy:
    build: proxy
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - backend
