server {
    listen       8090;
    location / {
        proxy_pass          http://backend.railway.internal:8080;
    }
}

server {
    listen       80;
    server_name localhost;
    location / {
        proxy_pass          http://localhost:8080;
    }
}